export const devicesListData = [
  {
    id: 1,
    name: "Gateway-01",
    subName: "Main Gateway",
    deviceId: "GW-0001",
    type: "Gateway",
    location: "Mumbai Site",
    subLocation: "",
    status: "Online",
    signal: "-65 dBm",
    signalBars: 4,
    lastSeen: "20 May 2025",
    subLastSeen: "10:24:35 AM",
    firmware: "v1.2.8",
  },
  {
    id: 2,
    name: "Gateway-02",
    subName: "Backup Gateway",
    deviceId: "GW-0002",
    type: "Gateway",
    location: "Pune Site",
    subLocation: "",
    status: "Online",
    signal: "-70 dBm",
    signalBars: 3,
    lastSeen: "20 May 2025",
    subLastSeen: "10:24:20 AM",
    firmware: "v1.2.7",
  },
  {
    id: 2,
    name: "Gateway-02",
    subName: "Backup Gateway",
    deviceId: "GW-0002",
    type: "Gateway",
    location: "Pune Site",
    subLocation: "",
    status: "Online",
    signal: "-70 dBm",
    signalBars: 3,
    lastSeen: "20 May 2025",
    subLastSeen: "10:24:20 AM",
    firmware: "v1.2.7",
  },
  {
    id: 2,
    name: "Gateway-02",
    subName: "Backup Gateway",
    deviceId: "GW-0002",
    type: "Gateway",
    location: "Pune Site",
    subLocation: "",
    status: "Online",
    signal: "-70 dBm",
    signalBars: 3,
    lastSeen: "20 May 2025",
    subLastSeen: "10:24:20 AM",
    firmware: "v1.2.7",
  },
  {
    id: 2,
    name: "Gateway-02",
    subName: "Backup Gateway",
    deviceId: "GW-0002",
    type: "Gateway",
    location: "Pune Site",
    subLocation: "",
    status: "Online",
    signal: "-70 dBm",
    signalBars: 3,
    lastSeen: "20 May 2025",
    subLastSeen: "10:24:20 AM",
    firmware: "v1.2.7",
  },
  {
    id: 3,
    name: "DCU-021",
    subName: "Floor-01 DCU",
    deviceId: "DCU-021",
    type: "DCU",
    location: "Mumbai Site",
    subLocation: "Gateway-02",
    status: "Online",
    signal: "-68 dBm",
    signalBars: 4,
    lastSeen: "20 May 2025",
    subLastSeen: "10:24:10 AM",
    firmware: "v1.1.5",
  },
  {
    id: 4,
    name: "DCU-022",
    subName: "Floor-02 DCU",
    deviceId: "DCU-022",
    type: "DCU",
    location: "Mumbai Site",
    subLocation: "Gateway-02",
    status: "Online",
    signal: "-72 dBm",
    signalBars: 3,
    lastSeen: "20 May 2025",
    subLastSeen: "10:23:58 AM",
    firmware: "v1.1.5",
  },
  {
    id: 5,
    name: "DCU-023",
    subName: "Floor-03 DCU",
    deviceId: "DCU-023",
    type: "DCU",
    location: "Mumbai Site",
    subLocation: "Gateway-02",
    status: "Offline",
    signal: "-",
    signalBars: 0,
    lastSeen: "20 May 2025",
    subLastSeen: "09:45:12 AM",
    firmware: "v1.1.4",
  },
  {
    id: 6,
    name: "Meter-003",
    subName: "Room 101 Meter",
    deviceId: "MTR-003",
    type: "Meter",
    location: "Mumbai Site",
    subLocation: "DCU-021",
    status: "Online",
    signal: "-73 dBm",
    signalBars: 3,
    lastSeen: "20 May 2025",
    subLastSeen: "10:24:30 AM",
    firmware: "v2.0.3",
  },
  {
    id: 7,
    name: "Meter-004",
    subName: "Room 102 Meter",
    deviceId: "MTR-004",
    type: "Meter",
    location: "Mumbai Site",
    subLocation: "DCU-021",
    status: "Online",
    signal: "-75 dBm",
    signalBars: 3,
    lastSeen: "20 May 2025",
    subLastSeen: "10:24:28 AM",
    firmware: "v2.0.3",
  },
  {
    id: 8,
    name: "Meter-005",
    subName: "Room 103 Meter",
    deviceId: "MTR-005",
    type: "Meter",
    location: "Mumbai Site",
    subLocation: "DCU-021",
    status: "Warning",
    signal: "-85 dBm",
    signalBars: 1,
    lastSeen: "20 May 2025",
    subLastSeen: "10:18:11 AM",
    firmware: "v2.0.2",
  },
  {
    id: 9,
    name: "Meter-006",
    subName: "Room 104 Meter",
    deviceId: "MTR-006",
    type: "Meter",
    location: "Mumbai Site",
    subLocation: "DCU-021",
    status: "Offline",
    signal: "-",
    signalBars: 0,
    lastSeen: "20 May 2025",
    subLastSeen: "08:02:45 AM",
    firmware: "v2.0.2",
  },
  {
    id: 10,
    name: "Meter-045",
    subName: "Room 201 Meter",
    deviceId: "MTR-045",
    type: "Meter",
    location: "Pune Site",
    subLocation: "DCU-041",
    status: "Online",
    signal: "-69 dBm",
    signalBars: 4,
    lastSeen: "20 May 2025",
    subLastSeen: "10:24:33 AM",
    firmware: "v2.0.3",
  },
];

export const devicesByTypeData = [
  { name: "Gateways", value: 12, percent: "3.5%", color: "#2563eb" },
  { name: "DCUs", value: 48, percent: "14.0%", color: "#9333ea" },
  { name: "Energy Meters", value: 282, percent: "82.5%", color: "#10b981" },
];

export const healthGaugeData = [
  { name: "Healthy", value: 308, percent: "90.1%", color: "#10b981" },
  { name: "Warning", value: 14, percent: "4.1%", color: "#f59e0b" },
  { name: "Offline", value: 20, percent: "5.8%", color: "#ef4444" },
];

export const gatewaysStatusData = [
  { gateway: "Gateway-01", status: "Online", connectedDCUs: "12 / 12", meters: 68, lastSeen: "10:24:35 AM" },
  { gateway: "Gateway-02", status: "Online", connectedDCUs: "10 / 12", meters: 56, lastSeen: "10:24:20 AM" },
  { gateway: "Gateway-03", status: "Warning", connectedDCUs: "8 / 12", meters: 42, lastSeen: "10:17:11 AM" },
  { gateway: "Gateway-04", status: "Offline", connectedDCUs: "0 / 12", meters: 0, lastSeen: "08:05:33 AM" },
];
