// src/components/locations/mockLocationsData.js

export const LOCATIONS_DATA = [
  {
    id: "DEL-001",
    name: "Delhi Site",
    address: "Sector 62, Noida\nUttar Pradesh, 201309",
    status: "Online",
    gateways: [
      {
        id: "GW-DEL-01",
        name: "Gateway-01",
        status: "Online",
        dcus: [
          {
            id: "DCU-DEL-101",
            name: "DCU-101",
            status: "Online",
            meters: [
              {
                id: "MTR-DEL-001",
                name: "Meter-001",
                status: "Online",
                model: "AR-3P-CT-100A",
                serialNo: "AR2025MTR0001",
                dcuName: "DCU-101",
                gatewayName: "Gateway-01",
                metrics: {
                  voltage: { val: "412.5", unit: "V", trend: "+0.5%", trendType: "up", sub: "Avg" },
                  current: { val: "17.40", unit: "A", trend: "+0.8%", trendType: "up", sub: "Avg" },
                  activePower: { val: "7.15", unit: "kW", trend: "-0.2%", trendType: "down", sub: "Avg" },
                  powerFactor: { val: "0.97", unit: "", trend: "+0.1%", trendType: "up", sub: "" },
                  frequency: { val: "50.01", unit: "Hz", trend: "", trendType: "neutral", sub: "Hz ≈ 0." },
                  totalEnergy: { val: "1,180.40", unit: "kWh", trend: "+1.9%", trendType: "up", sub: "Import" },
                },
                deviceInfo: {
                  meterId: "MTR-001",
                  model: "AR-3P-CT-100A",
                  serialNo: "AR2025MTR0001",
                  phase: "3 Phase - 4 Wire",
                  ctRating: "100A",
                  vtRating: "440V",
                  firmware: "v1.2.8",
                  lastUpdated: "20 May 2025 10:24:20 AM",
                  status: "Online",
                  connection: "Online",
                  signalStrength: "-65 dBm",
                  batteryLevel: "94%",
                  uptime: "4d 12h 10m",
                },
                realTimeParams: [
                  { param: "Voltage (V)", l1: "412.0", l2: "413.0", l3: "412.5", avg: "412.5" },
                  { param: "Current (A)", l1: "17.20", l2: "17.50", l3: "17.50", avg: "17.40" },
                  { param: "Active Power (kW)", l1: "2.35", l2: "2.40", l3: "2.40", avg: "7.15" },
                  { param: "Reactive Power (kVAr)", l1: "0.38", l2: "0.40", l3: "0.39", avg: "1.17" },
                  { param: "Apparent Power (kVA)", l1: "2.38", l2: "2.43", l3: "2.43", avg: "7.24" },
                  { param: "Power Factor", l1: "0.98", l2: "0.97", l3: "0.97", avg: "0.97" },
                  { param: "Frequency (Hz)", l1: "50.01", l2: "50.01", l3: "50.01", avg: "50.01" },
                ],
                powerTrendData: [
                  { time: "00:00", active: 5.8, reactive: 0.8, apparent: 6.2 },
                  { time: "02:00", active: 6.1, reactive: 0.7, apparent: 6.5 },
                  { time: "04:00", active: 6.0, reactive: 0.6, apparent: 6.4 },
                  { time: "06:00", active: 6.8, reactive: 0.7, apparent: 7.2 },
                  { time: "08:00", active: 7.4, reactive: 0.8, apparent: 7.8 },
                  { time: "10:00", active: 7.15, reactive: 0.7, apparent: 7.6 },
                  { time: "12:00", active: 7.3, reactive: 0.8, apparent: 7.7 },
                  { time: "14:00", active: 6.9, reactive: 0.7, apparent: 7.3 },
                  { time: "16:00", active: 7.0, reactive: 0.7, apparent: 7.4 },
                  { time: "18:00", active: 7.5, reactive: 0.8, apparent: 7.9 },
                  { time: "20:00", active: 7.2, reactive: 0.8, apparent: 7.6 },
                  { time: "22:00", active: 6.5, reactive: 0.7, apparent: 6.9 },
                ],
                energyImportExport: {
                  importKwh: "1,140.2",
                  exportKwh: "40.2",
                  importPct: "96.6%",
                  exportPct: "3.4%",
                  totalKwh: "1,180.4",
                },
                energySummary: {
                  today: "22.10 kWh",
                  thisWeek: "154.20 kWh",
                  thisMonth: "1,180.40 kWh",
                  totalLife: "14,210.50 kWh",
                },
                events: [
                  { time: "10:24:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                  { time: "10:19:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                  { time: "10:14:20 AM", type: "success", title: "Data Sync", sub: "Synchronized with gateway" },
                  { time: "10:09:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                ],
              },
              {
                id: "MTR-DEL-002",
                name: "Meter-002",
                status: "Online",
                model: "AR-3P-CT-100A",
                serialNo: "AR2025MTR0002",
                dcuName: "DCU-101",
                gatewayName: "Gateway-01",
                metrics: {
                  voltage: { val: "411.8", unit: "V", trend: "+0.3%", trendType: "up", sub: "Avg" },
                  current: { val: "15.80", unit: "A", trend: "+0.4%", trendType: "up", sub: "Avg" },
                  activePower: { val: "6.42", unit: "kW", trend: "-0.6%", trendType: "down", sub: "Avg" },
                  powerFactor: { val: "0.96", unit: "", trend: "-0.1%", trendType: "down", sub: "" },
                  frequency: { val: "50.00", unit: "Hz", trend: "", trendType: "neutral", sub: "Hz ≈ 0." },
                  totalEnergy: { val: "945.20", unit: "kWh", trend: "+1.5%", trendType: "up", sub: "Import" },
                },
                deviceInfo: {
                  meterId: "MTR-002",
                  model: "AR-3P-CT-100A",
                  serialNo: "AR2025MTR0002",
                  phase: "3 Phase - 4 Wire",
                  ctRating: "100A",
                  vtRating: "440V",
                  firmware: "v1.2.8",
                  lastUpdated: "20 May 2025 10:24:20 AM",
                  status: "Online",
                  connection: "Online",
                  signalStrength: "-68 dBm",
                  batteryLevel: "90%",
                  uptime: "3d 08h 45m",
                },
                realTimeParams: [
                  { param: "Voltage (V)", l1: "411.2", l2: "412.0", l3: "412.2", avg: "411.8" },
                  { param: "Current (A)", l1: "15.60", l2: "15.90", l3: "15.90", avg: "15.80" },
                  { param: "Active Power (kW)", l1: "2.10", l2: "2.16", l3: "2.16", avg: "6.42" },
                  { param: "Reactive Power (kVAr)", l1: "0.35", l2: "0.36", l3: "0.36", avg: "1.07" },
                  { param: "Apparent Power (kVA)", l1: "2.13", l2: "2.19", l3: "2.19", avg: "6.51" },
                  { param: "Power Factor", l1: "0.96", l2: "0.96", l3: "0.96", avg: "0.96" },
                  { param: "Frequency (Hz)", l1: "50.00", l2: "50.00", l3: "50.00", avg: "50.00" },
                ],
                powerTrendData: [
                  { time: "00:00", active: 5.2, reactive: 0.7, apparent: 5.6 },
                  { time: "02:00", active: 5.4, reactive: 0.6, apparent: 5.8 },
                  { time: "04:00", active: 5.5, reactive: 0.6, apparent: 5.9 },
                  { time: "06:00", active: 6.0, reactive: 0.7, apparent: 6.4 },
                  { time: "08:00", active: 6.5, reactive: 0.8, apparent: 6.9 },
                  { time: "10:00", active: 6.42, reactive: 0.7, apparent: 6.8 },
                  { time: "12:00", active: 6.6, reactive: 0.8, apparent: 7.0 },
                  { time: "14:00", active: 6.3, reactive: 0.7, apparent: 6.7 },
                  { time: "16:00", active: 6.4, reactive: 0.7, apparent: 6.8 },
                  { time: "18:00", active: 6.8, reactive: 0.8, apparent: 7.2 },
                  { time: "20:00", active: 6.5, reactive: 0.7, apparent: 6.9 },
                  { time: "22:00", active: 5.8, reactive: 0.6, apparent: 6.2 },
                ],
                energyImportExport: {
                  importKwh: "915.0",
                  exportKwh: "30.2",
                  importPct: "96.8%",
                  exportPct: "3.2%",
                  totalKwh: "945.2",
                },
                energySummary: {
                  today: "19.80 kWh",
                  thisWeek: "135.60 kWh",
                  thisMonth: "945.20 kWh",
                  totalLife: "11,850.00 kWh",
                },
                events: [
                  { time: "10:24:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                  { time: "10:19:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                  { time: "10:14:20 AM", type: "warning", title: "Load Threshold", sub: "Peak load at 85%" },
                  { time: "10:09:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "GW-DEL-02",
        name: "Gateway-02",
        status: "Online",
        dcus: [
          {
            id: "DCU-DEL-021",
            name: "DCU-021",
            status: "Online",
            meters: [
              {
                id: "MTR-DEL-003",
                name: "Meter-003",
                status: "Online",
                model: "AR-3P-CT-100A",
                serialNo: "AR2025MTR0003",
                dcuName: "DCU-021",
                gatewayName: "Gateway-02",
                metrics: {
                  voltage: { val: "415.2", unit: "V", trend: "+0.8%", trendType: "up", sub: "Avg" },
                  current: { val: "18.62", unit: "A", trend: "+1.2%", trendType: "up", sub: "Avg" },
                  activePower: { val: "7.68", unit: "kW", trend: "-0.5%", trendType: "down", sub: "Avg" },
                  powerFactor: { val: "0.98", unit: "", trend: "+0.1%", trendType: "up", sub: "" },
                  frequency: { val: "50.02", unit: "Hz", trend: "", trendType: "neutral", sub: "Hz ≈ 0." },
                  totalEnergy: { val: "1,245.60", unit: "kWh", trend: "+2.3%", trendType: "up", sub: "Import" },
                },
                deviceInfo: {
                  meterId: "MTR-003",
                  model: "AR-3P-CT-100A",
                  serialNo: "AR2025MTR0003",
                  phase: "3 Phase - 4 Wire",
                  ctRating: "100A",
                  vtRating: "440V",
                  firmware: "v1.2.8",
                  lastUpdated: "20 May 2025 10:24:20 AM",
                  status: "Online",
                  connection: "Online",
                  signalStrength: "-62 dBm",
                  batteryLevel: "92%",
                  uptime: "2d 14h 35m",
                },
                realTimeParams: [
                  { param: "Voltage (V)", l1: "414.8", l2: "415.6", l3: "415.2", avg: "415.2" },
                  { param: "Current (A)", l1: "18.40", l2: "18.75", l3: "18.72", avg: "18.62" },
                  { param: "Active Power (kW)", l1: "2.52", l2: "2.58", l3: "2.58", avg: "7.68" },
                  { param: "Reactive Power (kVAr)", l1: "0.42", l2: "0.44", l3: "0.43", avg: "1.29" },
                  { param: "Apparent Power (kVA)", l1: "2.55", l2: "2.62", l3: "2.61", avg: "7.78" },
                  { param: "Power Factor", l1: "0.99", l2: "0.98", l3: "0.98", avg: "0.98" },
                  { param: "Frequency (Hz)", l1: "50.01", l2: "50.02", l3: "50.03", avg: "50.02" },
                ],
                powerTrendData: [
                  { time: "00:00", active: 6.8, reactive: 0.9, apparent: 7.0 },
                  { time: "02:00", active: 6.9, reactive: 0.6, apparent: 7.8 },
                  { time: "04:00", active: 6.6, reactive: 0.7, apparent: 7.5 },
                  { time: "06:00", active: 7.4, reactive: 0.6, apparent: 8.2 },
                  { time: "08:00", active: 7.6, reactive: 0.7, apparent: 8.6 },
                  { time: "10:00", active: 7.8, reactive: 0.6, apparent: 8.2 },
                  { time: "12:00", active: 7.5, reactive: 0.7, apparent: 8.1 },
                  { time: "14:00", active: 7.2, reactive: 0.6, apparent: 7.8 },
                  { time: "16:00", active: 7.3, reactive: 0.7, apparent: 7.9 },
                  { time: "18:00", active: 7.9, reactive: 0.8, apparent: 8.5 },
                  { time: "20:00", active: 8.1, reactive: 0.8, apparent: 8.8 },
                  { time: "22:00", active: 7.4, reactive: 0.7, apparent: 8.0 },
                ],
                energyImportExport: {
                  importKwh: "1,245.6",
                  exportKwh: "45.6",
                  importPct: "96.5%",
                  exportPct: "3.5%",
                  totalKwh: "1,291.2",
                },
                energySummary: {
                  today: "24.35 kWh",
                  thisWeek: "168.75 kWh",
                  thisMonth: "1,245.60 kWh",
                  totalLife: "15,680.25 kWh",
                },
                events: [
                  { time: "10:24:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                  { time: "10:19:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                  { time: "10:14:20 AM", type: "warning", title: "Voltage Unbalance", sub: "Unbalance: 2.1%" },
                  { time: "10:09:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                ],
              },
              {
                id: "MTR-DEL-004",
                name: "Meter-004",
                status: "Online",
                model: "AR-3P-CT-100A",
                serialNo: "AR2025MTR0004",
                dcuName: "DCU-021",
                gatewayName: "Gateway-02",
                metrics: {
                  voltage: { val: "414.0", unit: "V", trend: "+0.4%", trendType: "up", sub: "Avg" },
                  current: { val: "16.90", unit: "A", trend: "+0.9%", trendType: "up", sub: "Avg" },
                  activePower: { val: "6.95", unit: "kW", trend: "+0.3%", trendType: "up", sub: "Avg" },
                  powerFactor: { val: "0.98", unit: "", trend: "+0.2%", trendType: "up", sub: "" },
                  frequency: { val: "50.01", unit: "Hz", trend: "", trendType: "neutral", sub: "Hz ≈ 0." },
                  totalEnergy: { val: "1,090.80", unit: "kWh", trend: "+2.1%", trendType: "up", sub: "Import" },
                },
                deviceInfo: {
                  meterId: "MTR-004",
                  model: "AR-3P-CT-100A",
                  serialNo: "AR2025MTR0004",
                  phase: "3 Phase - 4 Wire",
                  ctRating: "100A",
                  vtRating: "440V",
                  firmware: "v1.2.8",
                  lastUpdated: "20 May 2025 10:24:20 AM",
                  status: "Online",
                  connection: "Online",
                  signalStrength: "-60 dBm",
                  batteryLevel: "95%",
                  uptime: "5d 02h 15m",
                },
                realTimeParams: [
                  { param: "Voltage (V)", l1: "413.5", l2: "414.2", l3: "414.3", avg: "414.0" },
                  { param: "Current (A)", l1: "16.70", l2: "17.00", l3: "17.00", avg: "16.90" },
                  { param: "Active Power (kW)", l1: "2.30", l2: "2.33", l3: "2.32", avg: "6.95" },
                  { param: "Reactive Power (kVAr)", l1: "0.38", l2: "0.39", l3: "0.39", avg: "1.16" },
                  { param: "Apparent Power (kVA)", l1: "2.33", l2: "2.36", l3: "2.35", avg: "7.04" },
                  { param: "Power Factor", l1: "0.98", l2: "0.98", l3: "0.98", avg: "0.98" },
                  { param: "Frequency (Hz)", l1: "50.01", l2: "50.01", l3: "50.01", avg: "50.01" },
                ],
                powerTrendData: [
                  { time: "00:00", active: 5.6, reactive: 0.8, apparent: 6.0 },
                  { time: "02:00", active: 5.9, reactive: 0.7, apparent: 6.3 },
                  { time: "04:00", active: 6.1, reactive: 0.6, apparent: 6.5 },
                  { time: "06:00", active: 6.5, reactive: 0.7, apparent: 6.9 },
                  { time: "08:00", active: 7.0, reactive: 0.8, apparent: 7.4 },
                  { time: "10:00", active: 6.95, reactive: 0.7, apparent: 7.3 },
                  { time: "12:00", active: 7.1, reactive: 0.8, apparent: 7.5 },
                  { time: "14:00", active: 6.8, reactive: 0.7, apparent: 7.2 },
                  { time: "16:00", active: 6.9, reactive: 0.7, apparent: 7.3 },
                  { time: "18:00", active: 7.3, reactive: 0.8, apparent: 7.7 },
                  { time: "20:00", active: 7.0, reactive: 0.7, apparent: 7.4 },
                  { time: "22:00", active: 6.2, reactive: 0.6, apparent: 6.6 },
                ],
                energyImportExport: {
                  importKwh: "1,050.0",
                  exportKwh: "40.8",
                  importPct: "96.3%",
                  exportPct: "3.7%",
                  totalKwh: "1,090.8",
                },
                energySummary: {
                  today: "21.50 kWh",
                  thisWeek: "148.20 kWh",
                  thisMonth: "1,090.80 kWh",
                  totalLife: "13,400.00 kWh",
                },
                events: [
                  { time: "10:24:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                  { time: "10:19:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                  { time: "10:14:20 AM", type: "success", title: "Firmware Check", sub: "Firmware v1.2.8 active" },
                  { time: "10:09:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                ],
              },
              {
                id: "MTR-DEL-005",
                name: "Meter-005",
                status: "Online",
                model: "AR-3P-CT-100A",
                serialNo: "AR2025MTR0005",
                dcuName: "DCU-021",
                gatewayName: "Gateway-02",
                metrics: {
                  voltage: { val: "416.0", unit: "V", trend: "+0.9%", trendType: "up", sub: "Avg" },
                  current: { val: "19.10", unit: "A", trend: "+1.5%", trendType: "up", sub: "Avg" },
                  activePower: { val: "7.92", unit: "kW", trend: "-0.4%", trendType: "down", sub: "Avg" },
                  powerFactor: { val: "0.99", unit: "", trend: "+0.1%", trendType: "up", sub: "" },
                  frequency: { val: "50.02", unit: "Hz", trend: "", trendType: "neutral", sub: "Hz ≈ 0." },
                  totalEnergy: { val: "1,310.50", unit: "kWh", trend: "+2.5%", trendType: "up", sub: "Import" },
                },
                deviceInfo: {
                  meterId: "MTR-005",
                  model: "AR-3P-CT-100A",
                  serialNo: "AR2025MTR0005",
                  phase: "3 Phase - 4 Wire",
                  ctRating: "100A",
                  vtRating: "440V",
                  firmware: "v1.2.8",
                  lastUpdated: "20 May 2025 10:24:20 AM",
                  status: "Online",
                  connection: "Online",
                  signalStrength: "-61 dBm",
                  batteryLevel: "91%",
                  uptime: "6d 18h 20m",
                },
                realTimeParams: [
                  { param: "Voltage (V)", l1: "415.8", l2: "416.2", l3: "416.0", avg: "416.0" },
                  { param: "Current (A)", l1: "18.90", l2: "19.20", l3: "19.20", avg: "19.10" },
                  { param: "Active Power (kW)", l1: "2.62", l2: "2.65", l3: "2.65", avg: "7.92" },
                  { param: "Reactive Power (kVAr)", l1: "0.41", l2: "0.43", l3: "0.42", avg: "1.26" },
                  { param: "Apparent Power (kVA)", l1: "2.65", l2: "2.68", l3: "2.68", avg: "8.01" },
                  { param: "Power Factor", l1: "0.99", l2: "0.99", l3: "0.99", avg: "0.99" },
                  { param: "Frequency (Hz)", l1: "50.02", l2: "50.02", l3: "50.02", avg: "50.02" },
                ],
                powerTrendData: [
                  { time: "00:00", active: 6.9, reactive: 0.9, apparent: 7.2 },
                  { time: "02:00", active: 7.1, reactive: 0.7, apparent: 7.5 },
                  { time: "04:00", active: 6.8, reactive: 0.7, apparent: 7.3 },
                  { time: "06:00", active: 7.5, reactive: 0.8, apparent: 8.0 },
                  { time: "08:00", active: 8.0, reactive: 0.8, apparent: 8.5 },
                  { time: "10:00", active: 7.92, reactive: 0.7, apparent: 8.4 },
                  { time: "12:00", active: 8.1, reactive: 0.8, apparent: 8.6 },
                  { time: "14:00", active: 7.7, reactive: 0.7, apparent: 8.2 },
                  { time: "16:00", active: 7.8, reactive: 0.7, apparent: 8.3 },
                  { time: "18:00", active: 8.3, reactive: 0.8, apparent: 8.9 },
                  { time: "20:00", active: 8.0, reactive: 0.8, apparent: 8.6 },
                  { time: "22:00", active: 7.3, reactive: 0.7, apparent: 7.8 },
                ],
                energyImportExport: {
                  importKwh: "1,260.5",
                  exportKwh: "50.0",
                  importPct: "96.2%",
                  exportPct: "3.8%",
                  totalKwh: "1,310.5",
                },
                energySummary: {
                  today: "26.10 kWh",
                  thisWeek: "179.40 kWh",
                  thisMonth: "1,310.50 kWh",
                  totalLife: "16,920.00 kWh",
                },
                events: [
                  { time: "10:24:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                  { time: "10:19:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                  { time: "10:14:20 AM", type: "warning", title: "Harmonic THD", sub: "THD level: 3.2%" },
                  { time: "10:09:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                ],
              },
            ],
          },
          {
            id: "DCU-DEL-022",
            name: "DCU-022",
            status: "Online",
            meters: [
              {
                id: "MTR-DEL-006",
                name: "Meter-006",
                status: "Online",
                model: "AR-3P-CT-100A",
                serialNo: "AR2025MTR0006",
                dcuName: "DCU-022",
                gatewayName: "Gateway-02",
                metrics: {
                  voltage: { val: "413.5", unit: "V", trend: "+0.6%", trendType: "up", sub: "Avg" },
                  current: { val: "17.10", unit: "A", trend: "+0.7%", trendType: "up", sub: "Avg" },
                  activePower: { val: "7.05", unit: "kW", trend: "+0.1%", trendType: "up", sub: "Avg" },
                  powerFactor: { val: "0.97", unit: "", trend: "+0.1%", trendType: "up", sub: "" },
                  frequency: { val: "50.01", unit: "Hz", trend: "", trendType: "neutral", sub: "Hz ≈ 0." },
                  totalEnergy: { val: "1,120.00", unit: "kWh", trend: "+2.0%", trendType: "up", sub: "Import" },
                },
                deviceInfo: {
                  meterId: "MTR-006",
                  model: "AR-3P-CT-100A",
                  serialNo: "AR2025MTR0006",
                  phase: "3 Phase - 4 Wire",
                  ctRating: "100A",
                  vtRating: "440V",
                  firmware: "v1.2.8",
                  lastUpdated: "20 May 2025 10:24:20 AM",
                  status: "Online",
                  connection: "Online",
                  signalStrength: "-64 dBm",
                  batteryLevel: "93%",
                  uptime: "1d 22h 10m",
                },
                realTimeParams: [
                  { param: "Voltage (V)", l1: "413.0", l2: "413.8", l3: "413.7", avg: "413.5" },
                  { param: "Current (A)", l1: "16.90", l2: "17.20", l3: "17.20", avg: "17.10" },
                  { param: "Active Power (kW)", l1: "2.32", l2: "2.37", l3: "2.36", avg: "7.05" },
                  { param: "Reactive Power (kVAr)", l1: "0.38", l2: "0.40", l3: "0.39", avg: "1.17" },
                  { param: "Apparent Power (kVA)", l1: "2.35", l2: "2.40", l3: "2.39", avg: "7.14" },
                  { param: "Power Factor", l1: "0.97", l2: "0.97", l3: "0.97", avg: "0.97" },
                  { param: "Frequency (Hz)", l1: "50.01", l2: "50.01", l3: "50.01", avg: "50.01" },
                ],
                powerTrendData: [
                  { time: "00:00", active: 5.7, reactive: 0.8, apparent: 6.1 },
                  { time: "02:00", active: 6.0, reactive: 0.7, apparent: 6.4 },
                  { time: "04:00", active: 6.2, reactive: 0.6, apparent: 6.6 },
                  { time: "06:00", active: 6.6, reactive: 0.7, apparent: 7.0 },
                  { time: "08:00", active: 7.1, reactive: 0.8, apparent: 7.5 },
                  { time: "10:00", active: 7.05, reactive: 0.7, apparent: 7.4 },
                  { time: "12:00", active: 7.2, reactive: 0.8, apparent: 7.6 },
                  { time: "14:00", active: 6.9, reactive: 0.7, apparent: 7.3 },
                  { time: "16:00", active: 7.0, reactive: 0.7, apparent: 7.4 },
                  { time: "18:00", active: 7.4, reactive: 0.8, apparent: 7.8 },
                  { time: "20:00", active: 7.1, reactive: 0.7, apparent: 7.5 },
                  { time: "22:00", active: 6.3, reactive: 0.6, apparent: 6.7 },
                ],
                energyImportExport: {
                  importKwh: "1,080.0",
                  exportKwh: "40.0",
                  importPct: "96.4%",
                  exportPct: "3.6%",
                  totalKwh: "1,120.0",
                },
                energySummary: {
                  today: "22.50 kWh",
                  thisWeek: "152.00 kWh",
                  thisMonth: "1,120.00 kWh",
                  totalLife: "14,100.00 kWh",
                },
                events: [
                  { time: "10:24:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                  { time: "10:19:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                  { time: "10:14:20 AM", type: "success", title: "Status OK", sub: "Normal operation" },
                  { time: "10:09:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                ],
              },
            ],
          },
          {
            id: "DCU-DEL-023",
            name: "DCU-023",
            status: "Online",
            meters: [
              {
                id: "MTR-DEL-007",
                name: "Meter-007",
                status: "Online",
                model: "AR-3P-CT-100A",
                serialNo: "AR2025MTR0007",
                dcuName: "DCU-023",
                gatewayName: "Gateway-02",
                metrics: {
                  voltage: { val: "414.5", unit: "V", trend: "+0.5%", trendType: "up", sub: "Avg" },
                  current: { val: "17.80", unit: "A", trend: "+1.0%", trendType: "up", sub: "Avg" },
                  activePower: { val: "7.35", unit: "kW", trend: "-0.3%", trendType: "down", sub: "Avg" },
                  powerFactor: { val: "0.98", unit: "", trend: "+0.1%", trendType: "up", sub: "" },
                  frequency: { val: "50.01", unit: "Hz", trend: "", trendType: "neutral", sub: "Hz ≈ 0." },
                  totalEnergy: { val: "1,195.00", unit: "kWh", trend: "+2.2%", trendType: "up", sub: "Import" },
                },
                deviceInfo: {
                  meterId: "MTR-007",
                  model: "AR-3P-CT-100A",
                  serialNo: "AR2025MTR0007",
                  phase: "3 Phase - 4 Wire",
                  ctRating: "100A",
                  vtRating: "440V",
                  firmware: "v1.2.8",
                  lastUpdated: "20 May 2025 10:24:20 AM",
                  status: "Online",
                  connection: "Online",
                  signalStrength: "-63 dBm",
                  batteryLevel: "92%",
                  uptime: "4d 14h 00m",
                },
                realTimeParams: [
                  { param: "Voltage (V)", l1: "414.0", l2: "414.8", l3: "414.7", avg: "414.5" },
                  { param: "Current (A)", l1: "17.60", l2: "17.90", l3: "17.90", avg: "17.80" },
                  { param: "Active Power (kW)", l1: "2.42", l2: "2.47", l3: "2.46", avg: "7.35" },
                  { param: "Reactive Power (kVAr)", l1: "0.40", l2: "0.42", l3: "0.41", avg: "1.23" },
                  { param: "Apparent Power (kVA)", l1: "2.45", l2: "2.50", l3: "2.49", avg: "7.44" },
                  { param: "Power Factor", l1: "0.98", l2: "0.98", l3: "0.98", avg: "0.98" },
                  { param: "Frequency (Hz)", l1: "50.01", l2: "50.01", l3: "50.01", avg: "50.01" },
                ],
                powerTrendData: [
                  { time: "00:00", active: 6.2, reactive: 0.8, apparent: 6.6 },
                  { time: "02:00", active: 6.4, reactive: 0.7, apparent: 6.8 },
                  { time: "04:00", active: 6.5, reactive: 0.6, apparent: 6.9 },
                  { time: "06:00", active: 7.0, reactive: 0.7, apparent: 7.4 },
                  { time: "08:00", active: 7.4, reactive: 0.8, apparent: 7.9 },
                  { time: "10:00", active: 7.35, reactive: 0.7, apparent: 7.8 },
                  { time: "12:00", active: 7.6, reactive: 0.8, apparent: 8.0 },
                  { time: "14:00", active: 7.1, reactive: 0.7, apparent: 7.5 },
                  { time: "16:00", active: 7.2, reactive: 0.7, apparent: 7.6 },
                  { time: "18:00", active: 7.7, reactive: 0.8, apparent: 8.1 },
                  { time: "20:00", active: 7.3, reactive: 0.7, apparent: 7.7 },
                  { time: "22:00", active: 6.6, reactive: 0.6, apparent: 7.0 },
                ],
                energyImportExport: {
                  importKwh: "1,150.0",
                  exportKwh: "45.0",
                  importPct: "96.2%",
                  exportPct: "3.8%",
                  totalKwh: "1,195.0",
                },
                energySummary: {
                  today: "23.40 kWh",
                  thisWeek: "161.00 kWh",
                  thisMonth: "1,195.00 kWh",
                  totalLife: "14,800.00 kWh",
                },
                events: [
                  { time: "10:24:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                  { time: "10:19:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                  { time: "10:14:20 AM", type: "success", title: "Data Synced", sub: "Sync complete" },
                  { time: "10:09:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "GW-DEL-03",
        name: "Gateway-03",
        status: "Online",
        dcus: [
          {
            id: "DCU-DEL-031",
            name: "DCU-031",
            status: "Online",
            meters: [
              {
                id: "MTR-DEL-008",
                name: "Meter-008",
                status: "Online",
                model: "AR-3P-CT-100A",
                serialNo: "AR2025MTR0008",
                dcuName: "DCU-031",
                gatewayName: "Gateway-03",
                metrics: {
                  voltage: { val: "415.0", unit: "V", trend: "+0.7%", trendType: "up", sub: "Avg" },
                  current: { val: "18.20", unit: "A", trend: "+1.1%", trendType: "up", sub: "Avg" },
                  activePower: { val: "7.50", unit: "kW", trend: "-0.3%", trendType: "down", sub: "Avg" },
                  powerFactor: { val: "0.98", unit: "", trend: "+0.1%", trendType: "up", sub: "" },
                  frequency: { val: "50.02", unit: "Hz", trend: "", trendType: "neutral", sub: "Hz ≈ 0." },
                  totalEnergy: { val: "1,220.50", unit: "kWh", trend: "+2.2%", trendType: "up", sub: "Import" },
                },
                deviceInfo: {
                  meterId: "MTR-008",
                  model: "AR-3P-CT-100A",
                  serialNo: "AR2025MTR0008",
                  phase: "3 Phase - 4 Wire",
                  ctRating: "100A",
                  vtRating: "440V",
                  firmware: "v1.2.8",
                  lastUpdated: "20 May 2025 10:24:20 AM",
                  status: "Online",
                  connection: "Online",
                  signalStrength: "-62 dBm",
                  batteryLevel: "93%",
                  uptime: "3d 11h 25m",
                },
                realTimeParams: [
                  { param: "Voltage (V)", l1: "414.5", l2: "415.2", l3: "415.3", avg: "415.0" },
                  { param: "Current (A)", l1: "18.00", l2: "18.30", l3: "18.30", avg: "18.20" },
                  { param: "Active Power (kW)", l1: "2.47", l2: "2.52", l3: "2.51", avg: "7.50" },
                  { param: "Reactive Power (kVAr)", l1: "0.41", l2: "0.43", l3: "0.42", avg: "1.26" },
                  { param: "Apparent Power (kVA)", l1: "2.50", l2: "2.55", l3: "2.54", avg: "7.59" },
                  { param: "Power Factor", l1: "0.98", l2: "0.98", l3: "0.98", avg: "0.98" },
                  { param: "Frequency (Hz)", l1: "50.02", l2: "50.02", l3: "50.02", avg: "50.02" },
                ],
                powerTrendData: [
                  { time: "00:00", active: 6.5, reactive: 0.9, apparent: 6.9 },
                  { time: "02:00", active: 6.7, reactive: 0.7, apparent: 7.1 },
                  { time: "04:00", active: 6.8, reactive: 0.6, apparent: 7.2 },
                  { time: "06:00", active: 7.2, reactive: 0.7, apparent: 7.7 },
                  { time: "08:00", active: 7.7, reactive: 0.8, apparent: 8.2 },
                  { time: "10:00", active: 7.50, reactive: 0.7, apparent: 8.0 },
                  { time: "12:00", active: 7.8, reactive: 0.8, apparent: 8.3 },
                  { time: "14:00", active: 7.4, reactive: 0.7, apparent: 7.9 },
                  { time: "16:00", active: 7.5, reactive: 0.7, apparent: 8.0 },
                  { time: "18:00", active: 8.0, reactive: 0.8, apparent: 8.5 },
                  { time: "20:00", active: 7.6, reactive: 0.7, apparent: 8.1 },
                  { time: "22:00", active: 6.9, reactive: 0.6, apparent: 7.3 },
                ],
                energyImportExport: {
                  importKwh: "1,175.5",
                  exportKwh: "45.0",
                  importPct: "96.3%",
                  exportPct: "3.7%",
                  totalKwh: "1,220.5",
                },
                energySummary: {
                  today: "23.90 kWh",
                  thisWeek: "164.50 kWh",
                  thisMonth: "1,220.50 kWh",
                  totalLife: "15,100.00 kWh",
                },
                events: [
                  { time: "10:24:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                  { time: "10:19:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                  { time: "10:14:20 AM", type: "success", title: "Gateway Ping", sub: "Ping 18ms" },
                  { time: "10:09:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "MUM-002",
    name: "Mumbai Site",
    address: "Andheri East\nMumbai, Maharashtra",
    status: "Online",
    gateways: [
      {
        id: "GW-MUM-01",
        name: "Gateway-01",
        status: "Online",
        dcus: [
          {
            id: "DCU-MUM-011",
            name: "DCU-011",
            status: "Online",
            meters: [
              {
                id: "MTR-MUM-001",
                name: "Meter-101",
                status: "Online",
                model: "AR-3P-CT-100A",
                serialNo: "AR2025MTR1001",
                dcuName: "DCU-011",
                gatewayName: "Gateway-01",
                metrics: {
                  voltage: { val: "416.5", unit: "V", trend: "+0.8%", trendType: "up", sub: "Avg" },
                  current: { val: "19.50", unit: "A", trend: "+1.3%", trendType: "up", sub: "Avg" },
                  activePower: { val: "8.10", unit: "kW", trend: "+0.4%", trendType: "up", sub: "Avg" },
                  powerFactor: { val: "0.99", unit: "", trend: "+0.1%", trendType: "up", sub: "" },
                  frequency: { val: "50.03", unit: "Hz", trend: "", trendType: "neutral", sub: "Hz ≈ 0." },
                  totalEnergy: { val: "1,450.00", unit: "kWh", trend: "+2.6%", trendType: "up", sub: "Import" },
                },
                deviceInfo: {
                  meterId: "MTR-101",
                  model: "AR-3P-CT-100A",
                  serialNo: "AR2025MTR1001",
                  phase: "3 Phase - 4 Wire",
                  ctRating: "100A",
                  vtRating: "440V",
                  firmware: "v1.2.8",
                  lastUpdated: "20 May 2025 10:24:20 AM",
                  status: "Online",
                  connection: "Online",
                  signalStrength: "-59 dBm",
                  batteryLevel: "96%",
                  uptime: "7d 10h 15m",
                },
                realTimeParams: [
                  { param: "Voltage (V)", l1: "416.0", l2: "416.8", l3: "416.7", avg: "416.5" },
                  { param: "Current (A)", l1: "19.30", l2: "19.60", l3: "19.60", avg: "19.50" },
                  { param: "Active Power (kW)", l1: "2.68", l2: "2.71", l3: "2.71", avg: "8.10" },
                  { param: "Reactive Power (kVAr)", l1: "0.43", l2: "0.45", l3: "0.44", avg: "1.32" },
                  { param: "Apparent Power (kVA)", l1: "2.71", l2: "2.75", l3: "2.74", avg: "8.20" },
                  { param: "Power Factor", l1: "0.99", l2: "0.99", l3: "0.99", avg: "0.99" },
                  { param: "Frequency (Hz)", l1: "50.03", l2: "50.03", l3: "50.03", avg: "50.03" },
                ],
                powerTrendData: [
                  { time: "00:00", active: 7.0, reactive: 1.0, apparent: 7.4 },
                  { time: "02:00", active: 7.2, reactive: 0.8, apparent: 7.6 },
                  { time: "04:00", active: 7.1, reactive: 0.7, apparent: 7.5 },
                  { time: "06:00", active: 7.8, reactive: 0.8, apparent: 8.3 },
                  { time: "08:00", active: 8.3, reactive: 0.9, apparent: 8.8 },
                  { time: "10:00", active: 8.10, reactive: 0.8, apparent: 8.6 },
                  { time: "12:00", active: 8.4, reactive: 0.9, apparent: 8.9 },
                  { time: "14:00", active: 8.0, reactive: 0.8, apparent: 8.5 },
                  { time: "16:00", active: 8.1, reactive: 0.8, apparent: 8.6 },
                  { time: "18:00", active: 8.6, reactive: 0.9, apparent: 9.2 },
                  { time: "20:00", active: 8.2, reactive: 0.8, apparent: 8.7 },
                  { time: "22:00", active: 7.5, reactive: 0.7, apparent: 8.0 },
                ],
                energyImportExport: {
                  importKwh: "1,395.0",
                  exportKwh: "55.0",
                  importPct: "96.2%",
                  exportPct: "3.8%",
                  totalKwh: "1,450.0",
                },
                energySummary: {
                  today: "28.50 kWh",
                  thisWeek: "192.00 kWh",
                  thisMonth: "1,450.00 kWh",
                  totalLife: "18,200.00 kWh",
                },
                events: [
                  { time: "10:24:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                  { time: "10:19:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                  { time: "10:14:20 AM", type: "success", title: "Power Factor Peak", sub: "PF optimal at 0.99" },
                  { time: "10:09:20 AM", type: "success", title: "Data Updated", sub: "All parameters normal" },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];
