// src/data/mockLocationsData.js

export const LOCATIONS_DATA = [
  {
    id: "DEL-001",
    name: "Delhi Site",
    address: "Sector 62, Noida\nUttar Pradesh, 201309",
    status: "Online",
    gateways: [
      {
        id: "GW-DEL-01",
        name: "Gateway-01",
        status: "Online",
        dcus: [
          {
            id: "DCU-DEL-101",
            name: "DCU-101",
            status: "Online",
            meters: [
              {
                id: "MTR-DEL-001",
                name: "Meter-001",
                status: "Online",
                model: "AR-3P-CT-100A",
                serialNo: "AR2025MTR0001",
                dcuName: "DCU-101",
                metrics: {
                  voltage: 415.2,
                  current: 18.62,
                  activePower: 7.68,
                  powerFactor: 0.98,
                  frequency: 50.02,
                  totalEnergy: "1,245.60",
                },
                deviceInfo: {
                  meterId: "MTR-001",
                  model: "AR-3P-CT-100A",
                  serialNo: "AR2025MTR0001",
                  phase: "3 Phase - 4 Wire",
                  ctRating: "100A",
                  vtRating: "440V",
                  firmware: "v1.2.8",
                  lastUpdated: "20 May 2025 10:24 AM",
                  status: "Online",
                  signalStrength: "-62 dBm",
                  batteryLevel: "92%",
                },
                realTimeParams: [
                  { param: "Voltage (V)", p1: 415.6, p2: 414.8, p3: 415.2 },
                  { param: "Current (A)", p1: 18.4, p2: 18.75, p3: 18.72 },
                  { param: "Active Power (kW)", p1: 2.52, p2: 2.58, p3: 2.58 },
                  { param: "Reactive Power (kVAr)", p1: 0.42, p2: 0.44, p3: 0.43 },
                  { param: "Apparent Power (kVA)", p1: 2.55, p2: 2.62, p3: 2.61 },
                  { param: "Power Factor", p1: 0.99, p2: 0.98, p3: 0.98 },
                  { param: "Frequency (Hz)", p1: 50.01, p2: 50.02, p3: 50.03 },
                ],
              },
              {
                id: "MTR-DEL-002",
                name: "Meter-002",
                status: "Online",
                model: "AR-3P-CT-100A",
                serialNo: "AR2025MTR0002",
                dcuName: "DCU-101",
                metrics: {
                  voltage: 412.0,
                  current: 15.2,
                  activePower: 6.2,
                  powerFactor: 0.97,
                  frequency: 50.0,
                  totalEnergy: "980.40",
                },
                deviceInfo: {
                  meterId: "MTR-002",
                  model: "AR-3P-CT-100A",
                  serialNo: "AR2025MTR0002",
                  phase: "3 Phase - 4 Wire",
                  ctRating: "100A",
                  vtRating: "440V",
                  firmware: "v1.2.8",
                  lastUpdated: "20 May 2025 10:24 AM",
                  status: "Online",
                  signalStrength: "-65 dBm",
                  batteryLevel: "88%",
                },
                realTimeParams: [
                  { param: "Voltage (V)", p1: 412.0, p2: 411.5, p3: 412.5 },
                  { param: "Current (A)", p1: 15.1, p2: 15.3, p3: 15.2 },
                  { param: "Active Power (kW)", p1: 2.05, p2: 2.08, p3: 2.07 },
                  { param: "Reactive Power (kVAr)", p1: 0.35, p2: 0.38, p3: 0.36 },
                  { param: "Apparent Power (kVA)", p1: 2.08, p2: 2.11, p3: 2.1 },
                  { param: "Power Factor", p1: 0.97, p2: 0.97, p3: 0.97 },
                  { param: "Frequency (Hz)", p1: 50.0, p2: 50.0, p3: 50.0 },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "MUM-002",
    name: "Mumbai Site",
    address: "Andheri East\nMumbai, Maharashtra",
    status: "Online",
    gateways: [
      {
        id: "GW-MUM-02",
        name: "Gateway-02",
        status: "Online",
        dcus: [
          {
            id: "DCU-MUM-021",
            name: "DCU-021",
            status: "Online",
            meters: [
              {
                id: "MTR-MUM-003",
                name: "Meter-003",
                status: "Online",
                model: "AR-3P-CT-100A",
                serialNo: "AR2025MTR0003",
                dcuName: "DCU-021",
                metrics: {
                  voltage: 415.2,
                  current: 18.62,
                  activePower: 7.68,
                  powerFactor: 0.98,
                  frequency: 50.02,
                  totalEnergy: "1,245.60",
                },
                deviceInfo: {
                  meterId: "MTR-003",
                  model: "AR-3P-CT-100A",
                  serialNo: "AR2025MTR0003",
                  phase: "3 Phase - 4 Wire",
                  ctRating: "100A",
                  vtRating: "440V",
                  firmware: "v1.2.8",
                  lastUpdated: "20 May 2025 10:24 AM",
                  status: "Online",
                  signalStrength: "-62 dBm",
                  batteryLevel: "92%",
                },
                realTimeParams: [
                  { param: "Voltage (V)", p1: 415.6, p2: 414.8, p3: 415.2 },
                  { param: "Current (A)", p1: 18.4, p2: 18.75, p3: 18.72 },
                  { param: "Active Power (kW)", p1: 2.52, p2: 2.58, p3: 2.58 },
                  { param: "Reactive Power (kVAr)", p1: 0.42, p2: 0.44, p3: 0.43 },
                  { param: "Apparent Power (kVA)", p1: 2.55, p2: 2.62, p3: 2.61 },
                  { param: "Power Factor", p1: 0.99, p2: 0.98, p3: 0.98 },
                  { param: "Frequency (Hz)", p1: 50.01, p2: 50.02, p3: 50.03 },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];
